# .github/workflows/train-model.yml
name: Train Recipe Model

on:
  schedule:
    # Run once a week on Monday at 2am
    - cron: '0 2 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Trigger model training
        run: |
          curl -X POST "${{ secrets.RAILWAY_APP_URL }}/ai/trigger-training?force=false" -H "Content-Type: application/json"
               
      - name: Check training status
        run: |
          # Wait a bit for training to start
          sleep 10
          # Check status
          curl "${{ secrets.RAILWAY_APP_URL }}/ai/training-status" -H "Content-Type: application/json"